### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by spekulatius** [silverstripe-australia/silverstripe-gridfieldextensions#102]
Travis CI fails with this problem:

Problem 1
  - Installation request for silverstripe/framework 4.0.x-dev -> satisfiable by silverstripe/framework[4.0.x-dev].
  - silverstripe/framework 4.0.x-dev requires php >=5.4.0 -> no matching package found.

Can we fix this?

**Comment by kinglozzer** [comment]
So it looks like this errors as travis builds are run against PHP 5.3, when `master` requires 5.4. It *might* be possible to fix that, though given how far off SilverStripe 4 is I’d probably say it’s better to just build against the `3` branch instead of `master`:

```yml
env:
  - DB=MYSQL CORE_RELEASE=3.1
  - DB=MYSQL CORE_RELEASE=3
```

**Comment by spekulatius** [comment]
Yupp, I agree. It's a matter of setting it up correctly. Its just not a thing I can do that's why I raised the issue.
