### ISSUE TITLE
SS 3.2 GridFieldOrderableRows error on empty gridfield

### ISSUE THREAD

**Issue by mi32dogs** [silverstripe-australia/silverstripe-gridfieldextensions#111]
Hi and thank you for this great extension.
I'm getting an error on the GridFieldOrderableRows when i try to open a new record, that has a gridfield with relations in there.

whithin the getCMSFields:
$conf = GridFieldConfig_RelationEditor::create();
$conf->addComponent(new GridFieldOrderableRows('SortOrder'));
$conf->removeComponentsByType('GridFieldDeleteAction');
$conf->addComponent(new GridFieldDeleteAction(false));
$fields->addFieldToTab('Root.Seating Charts', new GridField('Seating', 'Seating Charts', $this->Seating(), $conf));

i get an error in the GridFieldOrderableRows.php and it works fine in 3.1.15

Thanks

**Comment by nyeholt** [comment]
What is the specific error? Also, are you adding the field _only_ once the parent object has been created (ie $this->ID > 0) ?

**Comment by mi32dogs** [comment]
sorry for the delay, i got almost the exact same error as the error in #113 
but i have now added the parent check and it is working fine
Thank you

**Comment by henrypenny** [comment]
@mi32dogs - could you please detail your solution a bit more?

**Comment by mi32dogs** [comment]
I simply warped it in an if statement like:
if($this->ID > 0) {
$conf = GridFieldConfig_RelationEditor::create();
$conf->addComponent(new GridFieldOrderableRows('SortOrder'));
$conf->removeComponentsByType('GridFieldDeleteAction');
$conf->addComponent(new GridFieldDeleteAction(false));
$fields->addFieldToTab('Root.Seating Charts', new GridField('Seating', 'Seating Charts', $this->Seating(), $conf));
}
so it will not show on a new record only on a edit
