### ISSUE TITLE
TextareaField in inline editing component gets pre-filled with random GridField HTML

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe-australia/silverstripe-gridfieldextensions#132]
SilverStripe 3.3. When using a `TextareaField` in the inline editing component, adding a new row will add a textarea that’s prefilled with the following HTML:

`<td class="col-buttons"> <button class="ss-gridfield-delete-inline gridfield-button-delete ss-ui-button" data-icon="cross-circle"></tbody></table>`

It appears that the new row template gets garbled by SilverStripe’s HTML parser. Logging this here in case anyone else comes across this or can think of a workaround, but this is probably a framework issue.

**Comment by feingestalten** [comment]
Same here (SilverStripe 3.2.x). Also when using some other Field types. But simple TextField and CheckboxField are working probably.

**Comment by kinglozzer** [comment]
Closed by https://github.com/silverstripe/silverstripe-framework/pull/5233
