### ISSUE TITLE
SS 3.3: sortTable can't be found for ManyManyExtraFields

### ISSUE THREAD

**Issue by xini** [silverstripe-australia/silverstripe-gridfieldextensions#134]
Using the DMS module, I get the following error:
```
Error at \gridfieldextensions\code\GridFieldOrderableRows.php line 135: Uncaught Exception: Couldn't find the sort field 'DocumentSort'
```
I have traced it back to line 116 of GridFieldOrderableRows where `$extra = $list->getExtraFields();` is empty. But I can't figure out why that is...

**Comment by MattyBalaam** [comment]
Same issue here

**Comment by xini** [comment]
@nyeholt any idea?

**Comment by nyeholt** [comment]
Not yet sorry, haven't been doing much 3.3 stuff just yet :(.

**Comment by xini** [comment]
No worries. It's just interesting how many things break with minor SS upgrades (which shouldnt include any breaking changes...)

**Comment by dhensby** [comment]
I can't replicate this issue

**Comment by xini** [comment]
resolved in 3.x-dev. See my comment in #80 (duplicate).
