### ISSUE TITLE
New release request (1.4.0)

### ISSUE THREAD

**Issue by tractorcow** [silverstripe-australia/silverstripe-gridfieldextensions#146]
@nyeholt would you please be able to tag a new release? there are quite a few fixes since 1.3.0 that would be nice to tag.

There seem to be a few new classes, so I'd guess 1.4.0 would be the next tag, following semantic versioning?

**Comment by nyeholt** [comment]
Just pushed a 1.4.0 tag :)

**Comment by tractorcow** [comment]
Yay thanks.
