### ISSUE TITLE
GridFieldOrderableRows: cannot reorder when Sort column values are not normalized

### ISSUE THREAD

**Issue by gregsmirnov** [silverstripe-australia/silverstripe-gridfieldextensions#149]
Imagine the situation when Sort field contains the same value, for example 1. Then reordering cannot reset Sort field the way it does with value 0 in GridFieldOrderableRows::populateSortValues(). And since the only valid Sort value in the set is 1, reordering will fail.

| Name   | Sort |
|-----------|-------|
| apple    |     1 |
| orange |      1 |
| pear     |      1 |

**Comment by jonom** [comment]
Fixed with https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/commit/1d2b20c87f792ca6b55bd1aaa01efda92a98b3f4 thanks @dhensby!

Not released yet though. Can we get a release please? `"silverstripe-australia/gridfieldextensions": "dev-master"` makes me uncomfortable 😛

**Comment by dhensby** [comment]
Yep, we need a release.

@jonom you can link to `1.4.x-dev` instead which will give you a little bit more certainty, but not much...

**Comment by nyeholt** [comment]
Have pushed a new release tag.
