### ISSUE TITLE
Regression: Can't reorder items if Sort column is not on base table

### ISSUE THREAD

**Issue by jonom** [silverstripe-australia/silverstripe-gridfieldextensions#155]
Think a bug has been introduced by #143 which results in an SQL error if you try to sort on a column that exists on a sub-class of a dataobject.

For example I have sub-classed `Link` from the Linkable module as `Spotlight` and added a `SortOrder` field to it. But when I try to enable drag and drop re-ordering for the gridfield, I get an SQL error because the `LastEdited` field doesn't exist on the `Spotlight` table (it's on the `Link` table).

Side note: it looks like that update causes all objects that have had their SortOrder modified to have their LastEdited date changed... that kind of makes sense to me but it's also misleading if you want to glean from the LastEdited date the last time the content of an item changed. You could easily reset every LastEdited value in a table by moving one item which seems like a bit of a loss of useful information to me. Maybe only the item that was dragged should have its LastEdited value updated?

I'd suggest reverting #143 and maybe separately update the LastEdited field on that one record. If you use the ORM instead of a raw statement it will update the correct (base) table.

**Comment by nyeholt** [comment]
@SilbinaryWolf - with #143, can this be changed as an interim fix to only add the `$additionalSql` if the `$table` referenced is a base data object class? 

Ultimately this should probably end up using the ORM stuff despite the overhead of loading and writing objects, as things like extensions should probably have a chance to interact post-sort too. And it may make it easier to address several other sort related bugs.

**Comment by SilbinaryWolf** [comment]
@nyeholt Looks like @dhensby has this PR'd: https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/pull/158/files

**Comment by dhensby** [comment]
Yep - if that PR get's merged I'll rebase my test to see if it passes :)

**Comment by dhensby** [comment]
This needs closing as it was resolved by #163
