### ISSUE TITLE
New branches for SS4 compatibility

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe-australia/silverstripe-gridfieldextensions#173]
Hi @nyeholt 

I'm going to send you through a PR shortly for SS4 compatibility.

Would you mind creating either a new branch off master to direct the PR at, or branching master off to a version branch for the current, so that master can become SS4 compatible from now on?

Cheers!

**Comment by nyeholt** [comment]
Hi @robbieaverill - how closely does it overlap with https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/pull/167 ?

**Comment by robbieaverill** [comment]
@nyeholt it's based from those changes, so entirely :)

**Comment by nyeholt** [comment]
Master has been updated with a new framework dependency and new branch-alias.

**Comment by robbieaverill** [comment]
Thanks!
