### ISSUE TITLE
Version tagging

### ISSUE THREAD

**Issue by harmoney-nikr** [silverstripe-australia/silverstripe-gridfieldextensions#97]
Would it be possible to start tagging revisions on this repo? I submitted #94 recently and really need it in our composer project, but the module is pulled in via another module's dependencies so I can't require `dev-master`.

**Comment by nyeholt** [comment]
Yep, I haven't got this module flagged in my version flagging script at present. Will try and get that sorted shortly.

**Comment by harmoney-nikr** [comment]
That was quick! Thanks, I'll check back in soon :smile:

**Comment by nyeholt** [comment]
Will be in meetings for a couple hours, so won't be until after that at least :)

**Comment by nyeholt** [comment]
That has been tagged

**Comment by harmoney-nikr** [comment]
Awesome, thanks for doing that so quickly!
